### ISSUE TITLE
Support for large input field

### ISSUE THREAD

**Issue by flexchar** [fourstacks/nova-repeatable-fields#14]
Hi,
thanks for great package! 

I was wondering, however, if you could add a support for larger (width, multiline) input fields. The change for width seems quite a simple, so as for swapping input type to textarea.

Current:
![image](https://user-images.githubusercontent.com/9198896/48671225-38fc8700-eb68-11e8-9b5e-afc3ac211168.png)
Area width change:
![image](https://user-images.githubusercontent.com/9198896/48671231-5a5d7300-eb68-11e8-99e0-19419de32e95.png)
Input -> textarea:
![image](https://user-images.githubusercontent.com/9198896/48671256-a4deef80-eb68-11e8-8394-51839e25ecf2.png)

**Comment by fourstacks** [comment]
Version 1.1.0 adds both textarea fields and also gives you the option of adding different width fields when using a non-stacked form (for example you could have a full width input followed by two half width inputs).

I'm not planning on supporting all the nova default fields just because this package works along fairly different lines but it would be cool.  If anyone figures this one out then PRs are open!

**Comment by flexchar** [comment]
@fourstacks Glad to hear that and I'd love to update! However, it seems that you forgot to update on Packagist, could you let me know when it's ready? :)

**Comment by fourstacks** [comment]
@flexchar - can you check again?  I can see v1.2.0 on packagist and the readme on there is up to date too.
