### ISSUE TITLE
Save data in different raws.

### ISSUE THREAD

**Issue by rmmaitrey** [fourstacks/nova-repeatable-fields#9]
Hi,
I am little bit new to Nova. I find this package very helpful.
My need is little but different.
**I want to add 5 records and it should be saved in 5 raw of my table table.**

I think this package makes array of all 5 records and save it in one single raw.
Is there any way in this package to achieve what I need ?

**Comment by fourstacks** [comment]
@rmmaitrey - Sorry for the slow reply.  I'm afraid currently there is no way to achieve what you are after with this package though I am considering building in the ability to hook into the save of the field so that you can save/retrieve data however you want.  Might be some time before I have the space to do this though so if you come up with a solution in the meantime and think others would benefit then PRs are open!
